### ISSUE TITLE
is this repository abandoned ? 

### ISSUE THREAD

**Issue by przygienda** [GrahamDennis/dot-rust#10]
I need to merge the color support up to pull my package up ? Is the author still around or do I have to completely fork the repo here and publish a new crate. Would be very unfortunate ...

**Comment by przygienda** [comment]
if necessary, I'm willing to take ownership BTW ...

**Comment by GrahamDennis** [comment]
Yes, I suppose it is abandoned. Happy to give it to you, would you like me to transfer the repo on GitHub? Does anything else need to be done?

**Comment by przygienda** [comment]
Yes, please, transfer the ownership and I'll maintain ... If you published on crates.io, pls transfer ownership there as well ...

**Comment by GrahamDennis** [comment]
apparently I can't transfer it to you right now as you have a fork. please remove the fork and I'll transfer ownership.

**Comment by GrahamDennis** [comment]
You are now the owner of the crate `dot` on crates.io https://crates.io/crates/dot

**Comment by przygienda** [comment]
crates.io ownership confirmed, fork repo deleted ...

**Comment by GrahamDennis** [comment]
You should now be able to accept the repo transfer.

**Comment by przygienda** [comment]
sigh, just looked @ it, expired couple hours ago. Can you redo pls ... I'll check tommorow. I don't read my email from github frequently ...

**Comment by GrahamDennis** [comment]
It said it was still being transferred to you, but I’ve cancelled that request and created a new one

**Comment by przygienda** [comment]
Thanks, all done. Released a new one ...
